"use client";

import React from "react";
import VerificationScorecard from "./VerificationScorecard";
import { VerificationScorecardData } from "@/app/actions/analyzeArticle";

interface VerificationDossierProps {
  articleId: string;
  articleTitle: string;
  sourceName: string;
  relatedSources?: any; // JSON array from database
  briefing: string | null; // Stores tl_dr
  category?: string;
  verification: VerificationScorecardData | null;
  framingMatrix: any[];
}

export default function VerificationDossier({
  relatedSources,
  briefing,
  verification,
  framingMatrix,
}: VerificationDossierProps) {
  const sourcesList = Array.isArray(relatedSources) ? relatedSources : [];

  // Parse the tl_dr briefing into paragraphs
  const paragraphs = briefing
    ? briefing
        .split(/\n\s*\n/)
        .map((p) => p.trim())
        .filter(Boolean)
    : [];

  return (
    <div className="max-w-2xl mx-auto px-4 py-8 bg-white dark:bg-slate-900 transition-colors duration-300 space-y-6">
      {/* 1. Verification Scorecard sitting at the top */}
      <VerificationScorecard data={verification} />

      {/* 2. Narrative Framing Matrix */}
      {framingMatrix && framingMatrix.length > 0 && (
        <div className="bg-slate-50 dark:bg-slate-800/40 border border-slate-200 dark:border-slate-700/60 rounded-xl p-5 mt-4 space-y-3.5 transition-colors">
          <div className="text-[10px] font-mono tracking-widest text-slate-500 dark:text-slate-400 uppercase select-none border-b border-slate-200 dark:border-slate-750 pb-2 font-semibold">
            NARRATIVE FRAMING MATRIX
          </div>
          
          <div className="divide-y divide-slate-200 dark:divide-slate-700/60">
            {framingMatrix.map((item, idx) => (
              <div
                key={idx}
                className="grid grid-cols-1 sm:grid-cols-4 gap-2 py-3.5 first:pt-0 last:pb-0 text-sm align-middle"
              >
                <div className="sm:col-span-1 font-bold text-slate-900 dark:text-slate-100 select-all">
                  {item.outlet}
                </div>
                <div className="sm:col-span-3 text-slate-600 dark:text-slate-400 italic">
                  {item.angle}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* 3. The TL;DR Wire summary */}
      {paragraphs.length > 0 ? (
        <div className="space-y-6 pt-2">
          {paragraphs.map((para, idx) => (
            <p
              key={idx}
              className="font-serif text-lg leading-relaxed text-slate-800 dark:text-slate-200"
            >
              {para}
            </p>
          ))}
          
          <div className="mt-6 pt-4 border-t border-slate-200 dark:border-slate-700 flex items-center gap-2">
            <span className="text-xs font-mono uppercase tracking-wider text-slate-500 dark:text-slate-400">
              📡 Report generated by TruthFeed Intelligence
            </span>
          </div>
        </div>
      ) : (
        /* Pulser Skeleton matching 2 paragraphs of text (fallback/safeguard) */
        <div className="animate-pulse space-y-6 pt-4">
          <div className="space-y-3">
            <div className="h-4 bg-slate-200 dark:bg-slate-800 rounded w-full" />
            <div className="h-4 bg-slate-200 dark:bg-slate-800 rounded w-11/12" />
            <div className="h-4 bg-slate-200 dark:bg-slate-800 rounded w-4/5" />
          </div>
          <div className="space-y-3">
            <div className="h-4 bg-slate-200 dark:bg-slate-800 rounded w-full" />
            <div className="h-4 bg-slate-200 dark:bg-slate-800 rounded w-11/12" />
            <div className="h-4 bg-slate-200 dark:bg-slate-800 rounded w-5/6" />
          </div>
        </div>
      )}

      {/* Sources Footer */}
      {sourcesList.length > 0 && (
        <div className="border-t border-slate-200 dark:border-slate-700 mt-8 pt-4">
          <div className="text-sm text-slate-500 flex flex-wrap items-center leading-relaxed">
            <span className="mr-1">Sources:</span>
            {sourcesList.map((item: any, idx: number) => (
              <React.Fragment key={idx}>
                {idx > 0 && <span className="mx-1.5">•</span>}
                <a
                  href={item.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="hover:underline text-slate-500 hover:text-slate-800 dark:hover:text-slate-350 transition-colors"
                >
                  {item.sourceName}
                </a>
              </React.Fragment>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
