"use client";

import React from "react";
import Link from "next/link";
import { ArrowLeft, FileText, ShieldAlert } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-100 flex flex-col font-sans transition-colors duration-300">
      {/* Navigation */}
      <nav className="border-b border-slate-200 dark:border-slate-800/80 bg-white/95 dark:bg-slate-900/95 backdrop-blur-md sticky top-0 z-50 transition-colors duration-300">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 h-14 flex items-center justify-between">
          <Link
            href="/"
            className="inline-flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-slate-500 hover:text-slate-800 dark:text-slate-400 dark:hover:text-slate-200 transition-colors"
          >
            <ArrowLeft className="h-4 w-4" />
            <span>Newsroom</span>
          </Link>
          <span className="font-bold text-sm text-slate-800 dark:text-slate-100 uppercase tracking-widest font-mono flex items-center gap-1.5">
            <FileText className="h-4 w-4 text-indigo-500 fill-indigo-500/10" />
            Legal
          </span>
          <div className="w-20" /> {/* Spacer */}
        </div>
      </nav>

      {/* Main Content Container */}
      <main className="flex-1 max-w-3xl w-full mx-auto px-4 sm:px-6 py-10 md:py-16 space-y-8">
        <div className="space-y-2 border-b border-slate-200 dark:border-slate-800 pb-6">
          <h1 className="text-3xl font-serif font-black tracking-tight text-slate-900 dark:text-white leading-tight">
            Terms & Conditions
          </h1>
          <p className="text-xs font-mono text-slate-400 dark:text-slate-500">
            Last Updated: June 12, 2026
          </p>
        </div>

        <div className="prose dark:prose-invert max-w-none text-xs text-slate-650 dark:text-slate-350 space-y-6 leading-relaxed">
          <p>
            Welcome to <strong>TruthFeed</strong>. By accessing or using our website, database, feeds, or associated services (the "Service"), you agree to be bound by these Terms & Conditions ("Terms"). If you do not agree, please do not use the Service.
          </p>

          <div className="space-y-3">
            <h2 className="text-sm font-bold uppercase tracking-wide text-slate-800 dark:text-slate-200 font-mono">
              1. Description of Service
            </h2>
            <p>
              TruthFeed is an open-source news feed aggregator and transparency client designed to allow users to compare bias, credibility ratings, and consensus scores across various mainstream news outlets. The summaries and metadata provided are generated by automated natural language processing pipelines and community annotations.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-sm font-bold uppercase tracking-wide text-slate-800 dark:text-slate-200 font-mono">
              2. User Accounts & Authentications
            </h2>
            <p>
              To access personalized preferences (including bookmarks, specific regional focus prioritizations, and community note features), you must authenticate through a registered account. You are responsible for maintaining the confidentiality of your session credentials.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-sm font-bold uppercase tracking-wide text-slate-800 dark:text-slate-200 font-mono">
              3. Account Deletion and Right to be Forgotten
            </h2>
            <p>
              We respect user privacy and data ownership. You have the right to request deletion of your account and all associated user data at any time. This can be executed instantly and autonomously via your <strong>Account Settings</strong>. Once clicked, all bookmarks, settings, and profile entries linked to your UUID in the PostgreSQL database will be permanently purged (cascade deletion). This action is irreversible.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-sm font-bold uppercase tracking-wide text-slate-800 dark:text-slate-200 font-mono">
              4. Community Contributions & Notes
            </h2>
            <p>
              Registered users may submit community annotations ("Community Notes") on syndicated articles to report factuality claims or submit missing reference URLs. By submitting a note, you grant TruthFeed an unrestricted, royalty-free, perpetual license to publish, display, and distribute the note. You agree not to submit notes containing illegal, hateful, or deliberately false information.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-sm font-bold uppercase tracking-wide text-slate-800 dark:text-slate-200 font-mono">
              5. Intellectual Property & Syndicate Content
            </h2>
            <p>
              Articles, excerpts, and headlines referenced by the Service are the property of their respective publishers. TruthFeed acts as a search indexer and directory. We link directly to original publisher source URLs and maintain attribution markers. If you are a publisher and wish to opt out of indexing, please contact us.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-sm font-bold uppercase tracking-wide text-slate-800 dark:text-slate-200 font-mono">
              6. Disclaimers of Warranties
            </h2>
            <p>
              The Service is provided "as is" and "as available" without warranties of any kind, either express or implied, including but not limited to warranties of factual accuracy, source credibility correctness, or uninterrupted availability.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-sm font-bold uppercase tracking-wide text-slate-800 dark:text-slate-200 font-mono">
              7. Amendments
            </h2>
            <p>
              We reserve the right to modify these Terms at any time. Changes will be posted directly on this URL. Continued use of the Service following any modifications constitutes your acceptance of the revised Terms.
            </p>
          </div>
        </div>

        {/* Footer Accent */}
        <div className="pt-6 border-t border-slate-200 dark:border-slate-800 flex items-center gap-2.5 text-[10px] text-slate-400 dark:text-slate-500 font-mono">
          <ShieldAlert className="h-4 w-4 text-slate-400" />
          <span>TruthFeed Compliance Desk · support@truthfeed.org</span>
        </div>
      </main>
    </div>
  );
}
